stationとpenthouse
4sumi/RoN_jp_sub pull request #6
Opened 2023-12-28 07:17 UTC by dynamiteOpanty

stationのsub_jpが無かった数名、またpenthouseの翻訳を追加・編集しました。
また、チュートリアルの文をいくつか修正しました。

2023-12-30 15:51 UTC, 4sumi requested changes
2点ご確認をお願いします！

- [ ] StationAlvarez
- [ ] StationMichaels

2023-12-30 15:51 UTC, 4sumi commented on VO/PenthouseCivilianMale_1/sub_jp.csv
good👍

2023-12-30 15:51 UTC, 4sumi commented on VO/PenthouseLaurie/sub_jp.csv
good👍

2023-12-30 15:51 UTC, 4sumi commented on VO/PenthouseSailor/sub_jp.csv
good👍

2023-12-30 15:51 UTC, 4sumi commented on VO/PenthouseSuspectMale_1/sub_jp.csv
good👍

2023-12-30 15:51 UTC, 4sumi commented on VO/PenthouseWife/sub_jp.csv
good👍

2023-12-30 15:51 UTC, 4sumi commented on VO/Station Trainer/sub_jp.csv
nice👍

2023-12-30 15:51 UTC, 4sumi commented on VO/StationAlvarez/sub_jp.csv
> +[BARK]Idle_8,この街マジで楽園だなぁ。,
~~~
[BARK]Idle_7,Another wonderful day in Los Sueños.,
[BARK]Idle_8,Another day in paradise.,
~~~

大きく変わらない台詞に見えますが訳語が結構違うのは若干気になりますがどうでしょうか？
2つのセリフの中間あたりのテンションで修正をお願いできますか？

2023-12-30 15:51 UTC, 4sumi commented on VO/StationDoc/sub_jp.csv
nice👍

2023-12-30 15:51 UTC, 4sumi commented on VO/StationMichaels/sub_jp.csv
> +[BARK]Idle_13,今はもうストリートで暮らしてなくて、時々、良かったと思う。時々、恋しくなる,
[IMO]
> [BARK]Idle_13,"Some days I'm glad I don't work the streets anymore. Others, I miss it.",

若干冗長なので、下記のような訳はいかがでしょうか

>ストリートの仕事から足を洗って良かったと思っているが、時々恋しくなる。

2023-12-30 15:51 UTC, 4sumi commented on VO/StationReed/sub_jp.csv
good👍

2023-12-30 22:29 UTC, dynamiteOpanty commented on VO/StationAlvarez/sub_jp.csv
> +[BARK]Idle_8,この街マジで楽園だなぁ。,
割と皮肉めいた感じなので、その感じを潰さないようにと意図していました。

Idle_7の方をIdle_8の方に近づける感じで修正します。

2023-12-30 22:33 UTC, dynamiteOpanty commented on VO/StationMichaels/sub_jp.csv
> +[BARK]Idle_13,今はもうストリートで暮らしてなくて、時々、良かったと思う。時々、恋しくなる,
ご提案に賛成して修正します。

2023-12-31 04:26 UTC, 4sumi approved these changes

2023-12-31 04:26 UTC, 4sumi commented
LGTM!

2023-12-31 04:27 UTC, merged